name: "2nd-order-Heun-unconditional" #same as the file name, try to do that for all testers

tester:
  _target_: 'testing.tester.Tester'

sampler:
  _target_: 'testing.EulerHeunSampler.EulerHeunSampler'

modes: ["unconditional"] #modes to test

checkpoint: None



sampling_params:
  same_as_training: False #if true, the sampling parameters will be the same as the ones used for training (sigma_data, sigma_min, sigma_max and rho)
  sde_hp:
    sigma_data: 0.05 #default for maestro
    sigma_min: 4e-5
    sigma_max: 10 #this is sigma_start
    rho: 10
  Schurn: 20
  Snoise: 1
  Stmin: 0
  Stmax: 10
  order: 2 #order of the sampler (1 or 2)
  T: 101 #number of discretizatio steprs
  schedule: "edm" #"log": log schedule using the parameters in sampling_params


posterior_sampling:
  zeta: 0.5 #zeta for the posterior sampling


#experiment configuration for different testing modes

unconditional:
  num_samples: 1
  audio_len: 65536


#logging configuration
wandb:
  use: True
  log_every: 10
  run_name: "2nd-order-Heun-unconditional"
